spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/enterprise_lms
spring.datasource.username=root
spring.datasource.password=nepal
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
server.port=8080

# GitHub OAuth Configuration
github.client.id=${GITHUB_CLIENT_ID:YOUR_GITHUB_CLIENT_ID}
github.client.secret=${GITHUB_CLIENT_SECRET:YOUR_GITHUB_CLIENT_SECRET}
github.redirect.uri=http://localhost:8080/api/github/callback